### ISSUE TITLE
ul list

### ISSUE THREAD

**Issue by edwinavg** [avxto/pigeon-js#1]
When I create a list for a menu , only prints the last element of the list.

![about](https://cloud.githubusercontent.com/assets/5390703/10788174/183e144c-7d76-11e5-9988-f1e7eb0ee2ab.png)

'nav': {
                'ul.#menu':{
                    'li.item':{'a [href="/"]':'inicio'},
                    'li.item':{'a [href="/about"]':'About'}
                }
            }

**Comment by avxto** [comment]
Hello, thank you for mentioning this issue. It seems that since the keys are the same JavaScript overwrites the data. I am currently not home so, I will fix this ASAP.

**Comment by avxto** [comment]
Okay, this is fixed.
Because JavaScript objects must have unique keys there is some trouble. 

A quick and dirty fix could have been adding identifiers to the keys: 
Example: 
```
'li.item$': {},
'li.item$$': {},
```

Or alternatively, you can make the the menu  key into an array of objects.
Example: 
```
{
    'nav': {
        'ul.#menu':[
            {'li.item':{'a[href="/"]':'inicio'}},
            {'li.item':{'a[href="/about"]':'About'}}
        ],
    }
}
```

**Comment by edwinavg** [comment]
First example work perfect, but second display this:
 
[object Object]
[object Object]

**Comment by avxto** [comment]
It should work, if you are using npm please update the package. I just tested it and the second example works fine.

**Comment by edwinavg** [comment]
Its work. Thanks.
